### ISSUE TITLE
Inconsistent type of `userInfo` across operating systems in JSONEncoder, JSONDecoder, PropertyListEncoder, PropertyListDecoder

### ISSUE THREAD

**Issue by tothambrus11** [swiftlang/swift-foundation#1515]
### Description

In MacOS 14, the `userInfo` property in the protocols mentoned above has the type ` [CodingUserInfoKey : Any]`. However, on MacOS 15, this is changed to ` [CodingUserInfoKey : any Sendable]`. The [documentation](https://developer.apple.com/documentation/foundation/propertylistdecoder) doesn't disclose any changes to the api over time, just shows the `any Sendable` version.

This change is particularly nasty because it appears when upgrading operating systems without changing the Package.swift's  platforms entry from `.macOS(.v14)` to `.macOS(.v15)`, so some colleagues who have a newer laptop cannot compile our code, but those on earlier macOS versions can.

We would be also happy to migrate to the latest API, but that doesn't work on Linux and Windows using Swift 6.1. However, it is consistent and works using Swift 6.2.

### Reproduction

Swift 6.1 reproduction of problem: https://godbolt.org/z/cEbfbz1x7
Same code using 6.2 works: https://godbolt.org/z/K5Wdzed7e

### Expected behavior

- Have `userInfo: [CodingUserInfoKey : Any]` iff macos version in Package.swift<= 14
- Have `userInfo: [CodingUserInfoKey : any Sendable]` iff macos version in Package.swift >= 15

### Environment

My local installation on Windows where it's inconsistent with macos 15:
```
Swift version 6.1.2 (swift-6.1.2-RELEASE)
Target: x86_64-unknown-windows-msvc
```
My linux installation in a devcontainer where it's also inconsistent with macos 15:
```
Swift version 6.1.2 (swift-6.1.2-RELEASE)
Target: x86_64-unknown-linux-gnu
```

### Additional information

[FoundationEssentials.swiftinterface.txt](https://github.com/user-attachments/files/22450649/FoundationEssentials.swiftinterface.txt)
Let me know if there is any additional information needed. The issue presents itself as the FoundationEssentials.swiftinterface containing the old `Any` version on Windows and Linux, so I attached the swiftinterface file.

**Comment by jmschonfeld** [comment]
Thanks for reporting this! There was a change to Foundation in this area: we did intentionally change the value in that dictionary to `any Sendable` to align with the coder types' `Sendable` conformance, so the newer annotation is intentional. However it sounds like there may be some additional variables in play here.

> This change is particularly nasty because it appears when upgrading operating systems without changing the Package.swift's platforms entry from .macOS(.v14) to .macOS(.v15), so some colleagues who have a newer laptop cannot compile our code, but those on earlier macOS versions can.

This change is not dependent upon your minimum deployment target in your package manifest, but rather what SDK you are building with (i.e. what version of Xcode you are building with). In the scenarios where this does and does not work, can you confirm what SDK / what Xcode you are building with? I suspect that your colleagues who have newer laptops may just have newer Xcodes and that is what is causing the difference. In particular, you should see `any Sendable` when building with Xcode 16.3 (macOS 15.2 SDK) or later, and `Any` with previous Xcode/SDK versions regardless of whether your package manifest specifies a macOS 15 or 14 deployment target.

> We would be also happy to migrate to the latest API, but that doesn't work on Linux and Windows using Swift 6.1. However, it is consistent and works using Swift 6.2.

Just to clarify, your provided code compiles with Swift 6.2 on Linux/Windows but not on Swift 6.1 on Linux/Windows? The change in Foundation landed in Swift 6.1 on Linux/Windows so it sounds like there may be a compiler change in play here as well.

This difference between `any Sendable` and `Any` is not supposed to be a compilation error but rather a compilation _warning_ in Swift 5 mode (it is only supposed to be an error in Swift 6 mode). However I do see in your godbolt link that with the Swift 6.1 compiler, this results in an error. @xedin it seems like this may be a compiler bug, but I see you transferred this issue from the swift repo to this repo - is it expected that the Swift 6.1 compiler diagnoses this as an error in Swift 5 mode instead of a warning? Was there a change in Swift 6.2 that downgrades this to a warning? I believe we had waited for all compiler changes to land before landing this change in Foundation, however perhaps something was not brought in to Swift 6.1

**Comment by xedin** [comment]
I a lot of errors where downgraded, especially as related to preconcurrency in 6.2 but there was not a change to cherry-pick that to 6.1 because it was already released.

**Comment by jmschonfeld** [comment]
It sounds like we had an ordering mistake in how these changes landed then. Unfortunately since 6.1 shipped last Spring, there's not much we can do about this in 6.1 now - as you mentioned @tothambrus11 it's indeed resolved in 6.2. As a workaround, I wonder if you could use:

```swift
#if compiler(>=6.1)
typealias UserInfoValue = any Sendable
#else
typealias UserInfoValue = Any
#endif
```

and then use `UserInfoValue` instead of `Any` for your dictionary - that way regardless of what SDK version you're building with, your subclass' property will always match the parent class. After you require using Swift 6.2 / Xcode 26 to build your project you could remove this workaround.

**Comment by tothambrus11** [comment]
Hi, thank you very much for the detailed explanation. I will gather the details soon.

Until then, inspired by your typealias, this is what worked for us (we always compile with at least compiler v6.1, so we only need to account for the differences between OSs in the 6.1 version, and from 6.2, use `any Sendable` always.

```swift
#if (compiler(>=6.1) && os(macOS)) || compiler(>=6.2)
public typealias UserInfoValue = any Sendable
#else
public typealias UserInfoValue = Any
#endif
```

**Comment by jmschonfeld** [comment]
I'm going to go ahead and close this as completed since the issue is not present in 6.2+ and there is a workaround identifier for 6.1
