### ISSUE TITLE
[Linux] Fail to link FoundationEssentials with Swift 6.4 and `--static-swift-stdlib`

### ISSUE THREAD

**Issue by sebsto** [swiftlang/swift-foundation#2254]
**Describe the bug**
`swift build` crashes on Linux Swift 6.4 when using `import FoundationEssentials` and `--static-swift-stdlib`

**To Reproduce**

```sh
mkdir temp && cd temp
swift package init --type executable
cat > Sources/temp/temp.swift <<EOF
#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

@main
struct Examples {
    static func main() {
        let _ = try? JSONEncoder().encode("Hello World")
    }
}
EOF

container run -it --rm -v .:/project swift:noble bash -c "swift --version && cd /project && swift build --static-swift-stdlib"
```

Error 

```txt 
error: link command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld: /usr/lib/swift_static/linux/libFoundationEssentials.a(String+IO.swift.o): in function `$s20FoundationEssentials19createTemporaryFile33_FC9EC52B075D2ACCFF86F1C9F84293BELL2at6inPath6prefix7options7variants5Int32V_SStSS_xSSAA4DataV14WritingOptionsVSSSgtKAA0E19SystemRepresentableRzRi_zlFAJ_SStSgSpys4Int8VGSgKXEfU_AA3URLV_Tg5Tf4nnnd_n':
/usr/bin/ld: /usr/lib/swift_static/linux/libFoundationEssentials.a(UUID.swift.o): in function `$s20FoundationEssentials4UUIDV11descriptionSSvgTm':
_ThreadLocal.swift.o:(.text+0x24): undefined reference to `_foundation_uuid_unparse_upper'
/usr/bin/ld: /usr/lib/swift_static/linux/libFoundationEssentials.a(UUID.swift.o): in function `$s20FoundationEssentials4UUIDVACycfCTf4d_n':
_ThreadLocal.swift.o:(.text+0x658): undefined reference to `_foundation_uuid_generate_random'

... (redacted for brevity
```

**Expected behavior**
Should not crash (6.3 is OK) 

**Configuration (please complete the following information):**
 - Swift Version: Swift version 6.4 (swift-6.4-RELEASE) Target: aarch64-unknown-linux-gnu
 - OS: Noble, AmazonLinux2023, maybe others too
 - OS Version: `docker pull swift:noble`

**Regression information:**
Same command works with 6.3.x

**Additional context**
https://github.com/awslabs/swift-aws-lambda-runtime/issues/699
