### ISSUE TITLE
Out-of-bounds write when base64 encoding with .omitPaddingCharacter and a line-length option

### ISSUE THREAD

**Issue by maxches99** [swiftlang/swift-foundation#2149]
**Describe the bug**

`Data.base64EncodedString(options:)` and `Data.base64EncodedData(options:)` write past the end of their output buffer when `.omitPaddingCharacter` is combined with `.lineLength64Characters` or `.lineLength76Characters`.

This is a memory-safety bug: the encoder writes 1–2 bytes beyond the buffer it was given. In debug builds this hits the `UnsafeMutableBufferPointer` bounds check and traps, so it is easy to notice. In release builds that check is a `_debugPrecondition` and is compiled out, so the write actually lands past the end of the allocation and corrupts adjacent heap memory.

It is not a rare edge case — it happens for **every input whose length is not a multiple of 3**, with either line-length option and any combination of line-ending options.

**To Reproduce**

```swift
let data = Data(repeating: 0xFF, count: 1)
_ = data.base64EncodedString(options: [.lineLength76Characters, .omitPaddingCharacter])
```

In a debug build this traps in the `UnsafeMutableBufferPointer` bounds check (signal 5):

```
Swift/UnsafeBufferPointer.swift:791: Fatal error
```

The same happens with `.lineLength64Characters` and with `base64EncodedData(options:)`.

**Expected behavior**

Encoding succeeds and the padding characters are omitted, i.e. the result is the padded output with the trailing `=` characters removed:

```swift
Data(repeating: 0xFF, count: 1)
    .base64EncodedString(options: [.lineLength76Characters, .omitPaddingCharacter])  // "/w"
```

**Configuration (please complete the following information):**

- Swift Version: swift-foundation `main` (fc629f0), built with a recent trunk toolchain
- OS: macOS
- OS Version: 26.3 — though the affected code path is platform-independent

**Regression information:**

`.omitPaddingCharacter` was introduced in #1195 and is available from FoundationPreview 6.3, so every version that ships the option is affected. There is no earlier working version.

**Additional context**

In `Sources/FoundationEssentials/Data/Data+Base64.swift`, `encodeComputeCapacity(bytes:options:)` reduces the allocated capacity by 1–2 bytes when `.omitPaddingCharacter` is set and `bytes % 3 != 0`:

```swift
let capacityWithoutBreaks = if options.contains(.omitPaddingCharacter) {
    switch bytes % 3 {
    case 0: ((bytes + 2) / 3) * 4
    case 1: ((bytes + 2) / 3) * 4 - 2
    case 2: ((bytes + 2) / 3) * 4 - 1
    default: fatalError()
    }
} else {
    ((bytes + 2) / 3) * 4
}
```

but `_encodeWithLineBreaks(input:buffer:length:options:)` — the path taken whenever a line-length option is set — hardcodes the flag to `false` and therefore always writes the `=` padding:

```swift
static func _encodeWithLineBreaks(
    input: UnsafeBufferPointer<UInt8>,
    buffer: UnsafeMutableBufferPointer<UInt8>,
    length: inout Int,
    options: Data.Base64EncodingOptions
) {
    let omitPaddingCharacter = false
    ...
```

So the buffer is sized for output *without* padding while the encoder writes output *with* padding.

This looks like a missed call site in #1195: that PR replaced the identical `let omitPaddingCharacter = false` line in `_encode` with `options.contains(.omitPaddingCharacter)` and taught `encodeComputeCapacity` about the new option, but left the line in `_encodeWithLineBreaks` as it was.

Worth noting that `encodeToData` discards the length written back by `_encode` and returns a `Data` of the full computed capacity, so the computed capacity has to match the number of bytes written exactly: over-allocating shows up as trailing NUL bytes (#1535), and under-allocating is this out-of-bounds write.

Honoring the option in `_encodeWithLineBreaks` makes `encodeComputeCapacity` exactly right as it is already written. Comparing the computed capacity against the number of bytes `_encodeWithLineBreaks` writes, for every input length in `0...20000` across all eight combinations of line-length and line-ending options, gives an exact match in every case, both with and without `.omitPaddingCharacter`.

I have a fix and tests ready and will open a PR.
